### ISSUE TITLE
reset reason 

### ISSUE THREAD

**Issue by espuno** [hkiam/HCPBridge#15]
I have the circuit with esp32 in use and it works well. I have from time to time a reset = 1. What could be the reason?

/sysinfo 

{"freemem":224004,"hostname":"esp32-xxxx","ip":"192.168.xxx.xxx","ssid":"xxx","wifistatus":3,"resetreason":1}

**Comment by MCLW** [comment]
Hi, I have the same behavior from time to time. Maybe the esp needs too much current for a wifi reconnect and the hörmann promatic can not handle this current. 

Try to reduce the wifi power.
WiFi.setTxPower(WIFI_POWER_18_5dBm)

Not tested from my side.

**Comment by espuno** [comment]
thank you! I am trying it out

**Comment by espuno** [comment]
i set tx power to minus_1dBm. This seems to work. My wifi connection is strong enough. 

WiFi.setTxPower(WIFI_POWER_MINUS_1dBm); // Sets WiFi RF power output to lowest level, lowest RF power usage
