### ISSUE TITLE
Frage: habt ihr eine kabelempfehlung

### ISSUE THREAD

**Issue by hohmannc85** [hkiam/HCPBridge#18]
Könnt ihr ein Kabel nennen, ich finde das rs485 nicht 6 polig :(

**Comment by shellyeah** [comment]
Die 6-poligen Kabel (6P6C) sind RJ12. RJ11, also 4-polig (4P4C) geht allerdings auch, da die beiden äußeren jeweils GND (Pins 1+2) und 25V (Pins 5+6) sind.

**Comment by hohmannc85** [comment]
Spitze danke!
