### ISSUE TITLE
RS485 Protocol

### ISSUE THREAD

**Issue by apfelsaft87** [hkiam/HCPBridge#5]
Hi,

thank you for your great work!

Do you have some more information about the protocol used on rs485. I want to connect it to a S7-1500 Siemens plc and was hoping you can help me a bit by providing some infos.

Thanks!

**Comment by AndiP1234** [comment]
maybe this is a little help for you:
https://github.com/hkiam/HCPBridge/blob/master/HCPBridgeESP32/src/hciemulator.cpp

**Comment by apfelsaft87** [comment]
Thanks and something like:

Baudrate, Parity, Flowcontrol, RTS On and Off Delay, Answer Timeout, and Slave Adress?

Thank you again!

**Comment by hkiam** [comment]
look here for details:
https://github.com/hkiam/HCPBridge/tree/master/Investigation

and the source code provide all informations too, e.g.:

https://github.com/hkiam/HCPBridge/blob/master/HCPBridgeESP32/src/main.cpp
RS485.begin(57600,SERIAL_8E1);

https://github.com/hkiam/HCPBridge/blob/master/HCPBridgeESP32/src/hciemulator.h
#define DEVICEID 0x02
#define BROADCASTID 0x00

...
