### ISSUE TITLE
Explain how to program the esp32

### ISSUE THREAD

**Issue by mic9119** [hkiam/HCPBridge#6]
Hi,
kann mir jemand erklären wie ich den esp32 programmiert bekomme. Hatte bisher nur Berührungspunkte mit Arduino IDE.

Gruß Michael

**Comment by hkiam** [comment]
Je nach verwendeten Board funktioniert es recht ähnlich. Im Web findet man auch zahlreiche Anleitungen.
z.B.: https://unsinnsbasis.de/esp32-erste-schritte/
