### ISSUE TITLE
Lampenstatus im WebUI bei manuellem Schalten nicht korrekt

### ISSUE THREAD

**Issue by asdt1803** [hkiam/HCPBridge#8]
Hallo,

ich habe das Problem, dass beim manuellen Schalten der Lampe im WebUI der Status nicht korrekt angezeigt wird. Die Lampe wird geschaltet, aber der Slider springt immer wieder in die "Off"-Stellung. Auf der Statusseite steht im JSON entsprechend dauerhaft "lamp":false, egal, ob die Lampe an ist, oder nicht. Bei Torfahrt zeigen Slider  und JSON den korrekten Status.

Was kann die Ursache dafür sein?

**Comment by Gifford47** [comment]
@asdt1803 hast du das problem schon gelöst? ich habe z.Z. dasselbe problem...

**Comment by asdt1803** [comment]
Hallo @Gifford47 , leider nein. Mir ist nicht ganz klar, wo der Unterschied zwischen manuellem und automatischem Schalten liegt und wo der Fehler im Code liegen könnte. @hkiam scheint das Projekt leider nicht mehr aktiv zu maintainen.

**Comment by Gifford47** [comment]
ich bin bei meinem [dev branch](https://github.com/Gifford47/HCPBridgeMqtt/tree/development) gerade dabei das problem zu fixen und ein paar andere dinge zu implementieren. vll findest du in naher zulunft ja die lösung

**Comment by Gifford47** [comment]
@asdt1803 das problem ist nun [gefixed ](https://github.com/Gifford47/HCPBridgeMqtt/issues/5)und ist in dem o.g. dev branch zu finden

**Comment by asdt1803** [comment]
Super, vielen Dank. Dann mache ich hier zu und wechsle auf deinen Branch.

**Comment by asdt1803** [comment]
Fixed by @Gifford47 here: https://github.com/Gifford47/HCPBridgeMqtt/tree/development
